# fly.toml app configuration file generated for propmet on 2025-10-29T23:32:09+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'propmet'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
